### ISSUE TITLE
podman scripts

### ISSUE THREAD

**Issue by omac777** [kng/visionfive2-docker#1]
If you prefer podman, you can do the following:

podman_build.sh
```
#!/bin/bash
podman build -t visionfive2:latest .
# NOTE:  -the . is to specify where to find the Dockerfile
# -built image is named localhost/visionfive2:latest
```

podman_shell.sh
```
#!/bin/bash
podman run --privileged --rm -v $(pwd)/mnt:/mnt -it localhost/visionfive2:latest $@
```

Afterwards:
```
time ./podman_shell.sh build_u-boot.sh
time ./podman_shell.sh build_opensbi.sh
time ./podman_shell.sh build_spl.sh
time ./podman_shell.sh build_kernel.sh
```

**Comment by kng** [comment]
Ok, I'll include these scripts. Or do you want to do a MR ?
But `--privileged` should not be needed ?!

**Comment by omac777** [comment]
building u-boot: 1min
building opensbi: 10s
building spl: 1s
kernel: 7.5 minutes.

**Comment by omac777** [comment]
the` --privileged `is necessary.

Otherwise you get this error:
```
$ podman run --rm -v $(pwd)/mnt:/mnt -it localhost/visionfive2:latest /bin/bash
root@de62bd4f8a94:/mnt# ls
ls: cannot open directory '.': Permission denied
```

There is another way by using `-v $(pwd)/mnt:/mnt:Z` which makes podman selinux relabeling if I understood correctly.

**Comment by omac777** [comment]
I'm only providing some tidbits for you to do as you wish, but I needed to resort to this as I am on fedora silverblue and using their standard podman.

**Comment by omac777** [comment]
You're a rockstar and thank you.  I wasn't able to build the binaries because I wasn't using the correct distro version.  I tried 22.10/22.04, but these didn't work.  Your container uses an older version of ubuntu which explains why it succeeded, but still you overcame all the issues and it's saving me time and I imagine it will save others time as well.

**Comment by omac777** [comment]
I'm used to kernels building for an hour and a half.  Your docker image and configuration really helped to save a lot of time. 7.5minutes to run `time ./podman_shell.sh build_kernel.sh` !!!
Awesome!!! Thank you so much.

**Comment by kng** [comment]
I updated the Dockerfile to include ncurses as well, if you want to do menuconfig.
Thanks for the kind words (: 
I'll try podman out some day, I only run official docker and docker.io for now.
Regarding the --privileged, did the Z work ? or is there some user privilege that is needed ?
I mean, if it's running as nobody/nogroup, just `chmod 777 mnt` before running the container ?

**Comment by omac777** [comment]
I've attached my actual output for the podman build of the different scripts you provided.  Thank you again for all this effort and consideration.

[myPodmanVF2BuildOutput26Jan2023.txt](https://github.com/kng/visionfive2-docker/files/10510793/myPodmanVF2BuildOutput26Jan2023.txt)

**Comment by omac777** [comment]
With respect to chmod of directories before running, I'm not for that.  I prefer to respect the selinux settings as-is on Fedora Silverblue.  I'm certain the Z method also works, but I prefer not to fiddle with any of the other docker command line options.  I did my best not to modify anything you had in place except flipping docker to podman and the privileged switch.

**Comment by omac777** [comment]
don't be afraid of podman.  It's entirely compatible with docker with exception to the selinux/security stuff.  In most use-cases I've migrated from docker to podman without any issues.  If you run with gui stuff within podman, migrating X to wayland is a painpoint, but developers should be building against new gui toolkits anyways by now.

**Comment by kng** [comment]
Thanks for the tips, I'll look in to it. I'm both building and running stuff in docker.
Could you try this instead of the `-v` with podman ? `--mount type=bind,source=$(pwd)/mnt,target=/mnt`

**Comment by kng** [comment]
Added the scripts, and in the readme
